### ISSUE TITLE
Feature / optimizations request

### ISSUE THREAD

**Issue by arnoudhgz** [EmicoEcommerce/Magento2RobinHq#13]
When looking into the New Relic reports I noticed that, especially with a large customer base, the search queries took quite some time on the Magento2 database.

We optimized this by adding some indexes on tables that the Robin integration uses and removing the search on telephone number. 
Now I understand this removing of telephone number in the search query is not desirable for all clients.

So I want to propose these features / optimizations:

**1. Make it configurable in the Magento backend which customer data can be searched by. So cofiguration for:**
* Email enabled/disabled
* Telephone enabled/disabled

**2. Make sure indexes exists on the specific columns you target**
* You can create these with Setup/Patch/Schema files
* Make sure you do not create an index when it already exists

**3. When both fields are enabled do not use an **OR** but do two separate queries**
* This optimizes the way tables are used and two small queries are easier to process than one big one
* When you keep using the **OR** the indexes *you created in point 2* will not be properly hit

**Your thoughts?**
I would like to know if this can be implemented or maybe partly. I can create a PR, but would rather not spend time on this if you don't want these optimizations.

**Tech hint:**
I currently only focussed on this file: https://github.com/EmicoEcommerce/Magento2RobinHq/blob/master/src/DataProvider/SearchDataProvider.php

**Comment by bramstroker** [comment]
Hi @arnoudhgz 
Good idea to make this configurable. Both fields have to be enabled by default, but than you have the option to disable it per client.

I'm surprised that no index is being used. When developing this feature I have tested against a large customer database (200K customers) and also verified the correct index was being used.
That's also the reason why filtering on telephone number is done `LIKE '0643%'` and not `LIKE `%0643%`', because MySQL should use an index this way.
Maybe something has changed in newer Magento versions or I did miss something during development.
Anyway if you can verify with the MySQL `EXPLAIN` command that no index is being used and you can add the correct one, that would be perfect.

3. Also quite surprised that MySQL is not using the correct index(es) when using an `OR` statement. I would assume this shouldn't make a difference, but the MySQL optimizer has it's quirks.
Please also double check with `EXPLAIN` if this is really the case before making any code changes.

Glad to see a PR with optimizations, so you can proceed if you'd like.

**Comment by arnoudhgz** [comment]
@bramstroker I found out the things I mentioned by doing the `Explain` ;)

By default there is no index on this field, so it would be impossible to hit these:
* customer_entity.email
* customer_address_entity.telephone

When I created the index for **customer_entity.email** that index was still not triggered. I also had to remove the **OR** for telephone.
_I could remove telephone, since the client does not use that for searching_

**Comment by igorwulff** [comment]
@bramstroker Any updates on this?

**Comment by bramstroker** [comment]
Sorry missed your two last updates on this one. Will come back to you with an answer tomorrow

**Comment by bramstroker** [comment]
@igorwulff 
PR is very welcome. You can make the telephone field optional by configuration as discussed before.
The missing indices can be added to the install script.

The grid tables seem to be part of every magento 2 installation so I don't see any major drawbacks in using those.
However they are managed by a cron so if realtime availability of the data is a MUST we cannot use grid tables in this case. Maybe we could also make this configurable to support both ways, so it can be chosen per client. What do you think?

**Comment by Swahjak** [comment]
@bramstroker These are some serious issues that are raised an have been left open voor more than a year. We're (I assume everybody using this extension has an agreement with RobinHQ) paying users. I love the fact that a module is made open source, but that does not mean that serious issue can be dealt with by "a PR is welcome". I'm going to assume that anything serious is covered by RobinHQ (and if not I'm going to give them a ring about this).

We're experiencing these issues as wel during high load. Mainly reading from the `sales_order` table is a serious issue because it often gets locked during checkout / payment. That's why Magento is using a async `sales_order_grid` table to read the grid from. But also the search query is extremely inefficient. To give some more examples of performance issues:

1. CustomerFactory:97 is used to collect order information on a customer level. It does this by loading all orders, with all order items, while only the COUNT(1), MAX(created_at) and SUM(grand_total - total_refunded) values are used.
2. SearchDataProvider:99 always searches for both e-mail (on a non-indexed column) and telephone (on a non-indexed column) while we could easily asume a query with `@` is searching for an e-mail adres (the same could be said for telephone and order id).
3. OrderDetailViewProvider:60 fetches the complete invoice, while only the date is required
4. OrderFactory:126 fetches the entire order collection (filtered by customer e-mail) to check if an order is the first order

While it's great for customer support to have all this information at hand, these queries are quite heavy on an already stressed Magento (they are slow in general, due to some indexing issues). Especially relying heavily on sales_order (and sales_order_items) makes it extra tricky. The 'if realtime data is a MUST' is not really applicable here, if one would search the order in Magento it would also use the `sales_order_grid` table. So only if we MUST be more realtime than Magento itself this would be an issue.

Is there any way the order details could be fetched only if requested? This would make it possible to only use the `sales_order_grid` table for listing and we would only rely on `sales_order` and `sales_order_item` when a user proceeds by clicking on a specific order.

Ps. This is not meant to bash, but as a paying customer I expect these issues to be solved on short notice.

**Comment by Swahjak** [comment]
Ok, I've been reading the docs (https://developers.robinhq.com/docs/dynamic-integration/) a bit and it seems that on some levels more information is gathered than needed (correct me if I'm wrong). For example the search endpoint could easily just use `sales_order_grid` and `customer_grid_flat`. Which (if I'm not mistaken, I haven't checked) has all columns covered by indices. Then there is the customerOrders endpoint which gets more information than needed, including an expensive query to see if the order `is_first_order`. That leaves us with some aggregated data in the CustomerFactory, which could be written to a custom customer attribute or could be queried using a group by. I'll post a merge request / code later with some raw work I've been writing up to patch this issue in our own store.

**Comment by bramstroker** [comment]
@Swahjak There are definitely some places which need some optimizations for huge databases / shops with heavy load.

We did some testing during the initial development of this module with a database with approx 200.000 orders. I am pretty sure I checked the correct usage of indices and did some proper profiling, so I don't know what changed in the meantime.

I agree using the sales order table for querying order history is not efficient and we should definitely use sales order grid which is less frequently written to and better optimized for querying. This seems a perfect fit for the search endpoint which sole purpose is to get a listing of orders/customers bases on there email/telephone. This could also be combined with your suggested change to only filter on email when you provide a `@` in the search query.

For the other endpoints profiling is needed to see where big bottlenecks are. There is more data required on these endpoints so we can not use just the order grid there. Things can maybe be optimized by using collections/resources directly, but this will have a negative impact on clarity and maintainability, so this should really be a last resort.

I have contacted RobinHQ about your remarks to see what we can do. We are a Magento agency and commissioned with the development of this module. We cannot do any development without their approval first.

Happy to see your contribution to this module, and we can definitely work together to improve the performance of the module so it won't have a big negative performance hit on your shop.

**Comment by Swahjak** [comment]
@bramstroker I'm still planning on the pull, just haven't got to posting it yet. While I see your point regarding "There is more data required on these endpoints so we can not use just the order grid there" we would be very happy to drop some information in favor of performance. Maybe this is something that could be an 'advanced' toggle to either use the 'complete' or 'performance' models. By using the `sales_order_grid` and `customer_grid_flat` on the listing endpoints we've reduced average response times significantly (search from ~10 to 1.5 seconds, order list from ~5 to ~1 second) while only dropping the sales data on the customer during search (which we are happy to drop since it doesn't really add anything to the experience).

**Comment by pmzandbergen** [comment]
Currently running into the same issue. Queries on `sales_order` are taking 1~3 seconds when filtering on `customer_email` since no index exists. For the `customer_entity` table there doesn't seems to be an issue since `Magento_Customer` contains an index over `email` and `website_id` by default (`CUSTOMER_ENTITY_EMAIL_WEBSITE_ID`).

Using the grid tables would be an option, however the grid doesn't use an index over `customer_email` by default. Therefore two solutions remain:

1. Add an index on `sales_order` for the `customer_email` column
2. Add an index on `sales_order_grid` for the `customer_email` column, modify the query to join the `sales_order` table to complete the data

Since this is such a basic field my preference would be option 1. I'll submit a PR in a sec.

**Comment by pmzandbergen** [comment]
PR https://github.com/EmicoEcommerce/Magento2RobinHq/pull/29
