### ISSUE TITLE
Unable to setup install module via deployment "Error while checking if topic is synchronous"

### ISSUE THREAD

**Issue by RaphaelBronsveld** [EmicoEcommerce/Magento2RobinHq#18]
Hi there,

We are currently unable to use this module in our staging / production environments due to failing deployments. 
Magento is reporting that it's unable to find the configuration path for the given topic (in this case emico.robinhq).

<img width="625" alt="Screenshot 2021-02-15 at 11 47 14" src="https://user-images.githubusercontent.com/42035462/107937185-dfbc7180-6f83-11eb-8642-e8b6b06c5688.png">

We've setup RabbitMQ specifically for this module, and Magento is able to connect with RabbitMQ (other queue's are registered @ RabbitMQ). But the `setup:db-schema:upgrade` command still fails.

How do we solve this?
Thanks in advance.

Magento version: 2.3.3
Module version: v1.2.0

**Comment by hnsr** [comment]
Confirming this issue with version 1.2.0 on a Magento 2.3.5-p2 install. 

In addition; is it possible at all to use this module without running RabbitMQ but using the MySQL queue backend instead, even if it is suboptimal?

**Comment by Raven-VS** [comment]
Hi Raphael,

After checking the AmqpPublisher.php, it seems the TOPIC_NAME is set to emico.robinhq.
From what I can make of your issue, you're currently using just 'robinhq'.

Could you confirm?

**Comment by RaphaelBronsveld** [comment]
Hi @Raven-VS , it is indeed emico.robinhq that's being reported as the topic. Sorry for the confusion, I updated the issue :)

**Comment by bramstroker** [comment]
@RaphaelBronsveld @hnsr Thanks for your reports.

I went ahead and tried to reproduce this issue, unfortunately I'm not able to reproduce this.

I have a clean Magento installation without any 3rd party extensions.
Using the following versions:
- Magento 2.3.3 Open Source
- RobinHQ module 1.2.0
- PHP 7.3.23

My env.php looks as follows:

```
<?php
   'queue' => [
        'amqp' => [
            'host' => '127.0.0.1',
            'port' => '5672',
            'user' => 'guest',
            'password' => 'guest',
            'virtualhost' => '/'
        ]
    ]
```

When I run `bin/magento setup:upgrade` the command finishes without any errors and I see the `emico.robinhq` exchange and queue appearing in the RabbitMQ GUI.
After deleting the exchanges and queues and running setup upgrade again these are created nicely again.

Also when I place an new order I see the message appearing in the RabbitMQ queue.

I can remember I had this error before in some other Magento installation, but this was not related to the RobinHQ module. Not sure how this was solved.
I will ask some colleagues tomorrow if they know the potential cause of this issue.

A few questions.
Do you also have this issue with 1.1.3 or only with 1.2.0?
Do you see an exchange `emico.robinhq` in RabbitMQ interface? If so, could you try deleting it and run setup again.
Did this error start appearing immediately after you installed the RobinHQ module?
Is the rabbitmq broker correctly accessible and you use the right host/credentials?

@hnsr to answer your question about support for a DB queue. This is not implemented at the moment. I think it will be not too much effort to implement, but I have to discuss this with RobinHQ if they want use to proceed with this new development.

**Comment by bramstroker** [comment]
Also I see this exception is thrown in:

```
vendor/magento/framework-message-queue/Topology/Config/QueueConfigItem/DataMapper.php:133
```

Here the exception is catched and rethrown, however the real exception (root cause is lost).

```
} catch (LocalizedException $e) {
    throw new LocalizedException(new Phrase('Error while checking if topic is synchronous'));
}
```

So you'd need to put a breakpoint in the catch so the "real" exception is revealed which should give some clues why this exception is thrown in your installation.

Hope this helps.

**Comment by martin-emico** [comment]
This problem happens because it seems that bin/magento setup:upgrade is not flushing all the cache for the topic config data. 

If you look at the function getTopic (`vendor/magento/framework/Communication/Config.php:37` ) The data for the new added topic is null and it throws the error : Topic "%topic" is not configured. After flushing the cache the new topic exists.

I fixed this in the deploy to do a cache flush before the setup:upgrade.

For Example:
`# Deploy Commands`
`$configuration->addDeployCommand(new MaintenanceMode());`
`$configuration->addDeployCommand(new CacheFlush());`
`$configuration->addDeployCommand(new SetupUpgrade());`
