### ISSUE TITLE
Security issues when using FPC/varnish

### ISSUE THREAD

**Issue by reense** [EmicoEcommerce/Magento2RobinHq#44]
Hello,

We've found a security issue with this module when using FPC/varnish. Because this module implemented the routes via the default frontend router (etc/frontend/routes.xml), pages can be stored in the cache. So if the RobinHQ platform calls a route with a valid API username/password, Magento returns a 200 with the order information, and the page gets stored in the full pace cache. When a user then calls the URL without a username or password, the page is returned from the full page cache, without any authorization.

My suggestion would be to implement all the routes via a webapi.xml file with a custom authorization logic, so that you can keep checking for the auth header.

**Comment by bramstroker** [comment]
Thanks for raising the issue.

The main issue here is Varnish caching the response which it shouldn't because the response has an authorization header.
Whether this is basic auth, bearer authorization or any other kind, this should not matter because Varnish is unagnostic in that sense. By default a resources should never be cached by varnish when it has an authorization header.
This sounds like a configuration issue in the VCL of your application to me.

I have also checked with a few webshops we are maintaining and also ran the RobinHQ module with Varnish in front and I am unable to reproduce.

Here is a snippet from the varnishlog:

`varnishlog -q 'ReqUrl ~ "robinhq/api/order"'`


```
-   ReqHeader      X-Forwarded-Proto: https
-   ReqHeader      Connection: close
-   ReqHeader      user-agent: insomnia/2022.4.2
-   ReqHeader      authorization: Basic xxxxxxxxxxxx
-   ReqHeader      accept: */*
-   ReqHeader      cookie: PHPSESSID=xxxxxx
-   ReqUnset       X-Forwarded-For: 188.239.177.62
-   ReqHeader      X-Forwarded-For: 188.239.177.62, 127.0.0.1
-   VCL_call       RECV
-   ReqHeader      grace: none
-   ReqURL         /robinhq/api/order?orderNumber=000000001
-   VCL_return     hash
-   VCL_call       HASH
-   VCL_return     lookup
-   VCL_call       MISS
-   VCL_return     fetch
-   Link           bereq 580247482 fetch
-   Timestamp      Fetch: 1659424670.122689 0.173514 0.173514
```

As you can see the `authorization: Basic` header is received correctly by varnish and it is marked as a `MISS` because it is uncachable due to authorization header being present.
I have masked the basic auth value and PHPSESSID as it is sensitive information.

PS. the reason why we are not using the magento REST api (webapi) is because we need to adhere to the endpoints (URLs and JSON structure) and authentication method RobinHQ specifies. Their dashboard application calls these endpoints (and expects this structure) and afaik Magento is not the only application providing these endpoints for RobinHQ.
